name: Build Quartz64 Images
on: workflow_dispatch
jobs:
  build_uboot:
    strategy:
      matrix:
        boards: [
          {
            name: "Quartz64 Model A",
            uboot-config: "quartz64-a-rk3566_defconfig",
            uboot-name: "quartz64a"
          },
          {
            name: "Quartz64 Model B",
            uboot-config: "quartz64-b-rk3566_defconfig",
            uboot-name: "quartz64b"
          },
          {
            name: "SOQuartz",
            uboot-config: "soquartz-rk3566_defconfig",
            uboot-name: "soquartz"
          },
          {
            name: "EVB",
            uboot-config: "evb-rk3568_defconfig",
            uboot-name: "evb-rk3568"
          },
        ]
    runs-on: ubuntu-22.04
    steps:
      - name: Install toolchain
        run: |
            sudo apt-get update
            sudo apt-get install build-essential crossbuild-essential-arm64 device-tree-compiler
      #- name: Clone rkbin repository
      #  uses: actions/checkout@v3
      #  with:
      #    repository: 'rockchip-linux/rkbin'
      #    path: 'rkbin'
      - name: Clone u-boot repository
        uses: actions/checkout@v3
        with:
          repository: 'CounterPillow/u-boot-quartz64'
          ref: 'deploy'
          path: 'u-boot-quartz64'
      - name: Clean u-boot
        run: |
          cd u-boot-quartz64
          make mrproper
      - name: Fetch old rkbins
        run: |
          wget -q https://github.com/JeffyCN/rockchip_mirrors/blob/6186debcac95553f6b311cee10669e12c9c9963d/bin/rk35/rk3568_bl31_v1.28.elf?raw=true -O u-boot-quartz64/bl31.elf
          wget -q https://github.com/JeffyCN/rockchip_mirrors/blob/47404a141a1acb7555906b5e3b097b5f1045cc21/bin/rk35/rk3568_ddr_1560MHz_v1.11.bin?raw=true -O u-boot-quartz64/ram_init.bin
      - name: Build u-boot
        run: |
          cd u-boot-quartz64
          make ARCH=arm CROSS_COMPILE=aarch64-linux-gnu- ${{ matrix.boards.uboot-config }}
          make ARCH=arm CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
      - name: Archive u-boot artifacts
        uses: actions/upload-artifact@v3
        with:
          name: u-boot-${{ matrix.boards.uboot-name }}
          path: |
            u-boot-quartz64/u-boot.itb
            u-boot-quartz64/idbloader.img
  build_kernel:
    runs-on: self-hosted
    steps:
      - name: Clone workflow repository
        uses: actions/checkout@v3
      - name: Install toolchain
        run: |
            sudo apt-get -yq update && sudo apt-get -yq upgrade
            sudo apt-get -yq install build-essential crossbuild-essential-arm64 device-tree-compiler \
            autoconf bc bison flex ccache cpio dkms fakeroot kmod quilt rsync dh-exec \
            libssl-dev libncurses-dev libelf-dev libudev-dev libpci-dev libiberty-dev
      - name: Clone kernel repository
        uses: actions/checkout@v3
        with:
          repository: 'CounterPillow/linux'
          ref: 'quartz64-deploy'
          path: 'linux'
      - name: Make config
        run: |
          cp config linux/.config
          cd linux
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig
      - name: Build kernel
        run: |
          cd linux
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- deb-pkg
      - name: Archive kernel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-kernel
          path: |
            linux-image-*.deb
            linux-libc-dev*.deb
            !linux-image-*dbg*.deb
  build_dt_debs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone workflow repository
        uses: actions/checkout@v3
      - name: Install toolchain
        run: |
            sudo apt-get -yq update && sudo apt-get -yq upgrade
            sudo apt-get -yq install build-essential crossbuild-essential-arm64 device-tree-compiler \
            autoconf bc bison flex ccache cpio dkms fakeroot kmod quilt rsync dh-exec \
            libssl-dev libncurses-dev libelf-dev libudev-dev libpci-dev libiberty-dev
      - name: Build Device Tree Deb Package
        run: |
          cd deb-pkg
          ./build-devicetree-deb.sh
      - name: Archive Device Tree Debs
        uses: actions/upload-artifact@v3
        with:
          name: devicetrees-plebian-quartz64
          path: |
            deb-pkg/*.deb
  build_image:
    strategy:
      matrix:
        boards: [
          {
            name: "Quartz64 Model A",
            debos-yaml: "debian-quartz64a.yaml",
            uboot-name: "quartz64a"
          },
          {
            name: "Quartz64 Model B",
            debos-yaml: "debian-quartz64b.yaml",
            uboot-name: "quartz64b"
          },
          {
            name: "SOQuartz CM4 IO Board",
            debos-yaml: "debian-soquartz-cm4.yaml",
            uboot-name: "soquartz"
          },
        ]
    runs-on: ubuntu-22.04
    needs:
      - build_uboot
      - build_kernel
    env:
      GOPATH: /opt/src/gocode
    steps:
      - name: Clone workflow repository
        uses: actions/checkout@v3
      - name: Download u-boot artifacts
        uses: actions/download-artifact@v3
        with:
          name: u-boot-${{ matrix.boards.uboot-name}}
          path: debos-recipes/u-boot/
      - name: Download kernel artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-kernel
          path: debos-recipes/overlays/linux-kernel/
      - name: Install debos dependencies
        run: |
          sudo apt-get update
          sudo apt-get install golang git libglib2.0-dev libostree-dev \
                               qemu-system-x86 qemu-user-static debootstrap \
                               systemd-container
      - name: Install debos
        run: go install -v github.com/go-debos/debos/cmd/debos@latest
      - name: Build ${{ matrix.boards.name }} Image
        run: sudo /opt/src/gocode/bin/debos --disable-fakemachine debos-recipes/${{ matrix.boards.debos-yaml }}
      - name: Archive image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.boards.name }} Image
          path: |
            *.img.xz
